language: python
matrix:
  include:
    - python: "2.7"
      env: TORNADO_VERSION=HH ; WITH_RAVEN=1 ; WITH_FUTURES=1
    - python: "2.7"
      env: TORNADO_VERSION=HH ; WITH_RAVEN=0 ; WITH_FUTURES=0
    - python: "2.7"
      env: TORNADO_VERSION=3.2.2 ; WITH_RAVEN=1 ; WITH_FUTURES=1
    - python: "2.7"
      env: TORNADO_VERSION=3.2.2 ; WITH_RAVEN=1 ; WITH_FUTURES=0
    - python: "3.3"
      env: TORNADO_VERSION=HH ; WITH_RAVEN=1 ; WITH_FUTURES=0
    - python: "3.3"
      env: TORNADO_VERSION=HH ; WITH_RAVEN=0 ; WITH_FUTURES=0
    - python: "3.3"
      env: TORNADO_VERSION=3.2.2 ; WITH_RAVEN=1 ; WITH_FUTURES=0
    - python: "3.4"
      env: TORNADO_VERSION=HH ; WITH_RAVEN=1 ; WITH_FUTURES=0
    - python: "3.4"
      env: TORNADO_VERSION=HH ; WITH_RAVEN=0 ; WITH_FUTURES=0
    - python: "3.4"
      env: TORNADO_VERSION=3.2.2 ; WITH_RAVEN=1 ; WITH_FUTURES=0
    - python: "3.5"
      env: TORNADO_VERSION=HH ; WITH_RAVEN=1 ; WITH_FUTURES=0
    - python: "3.5"
      env: TORNADO_VERSION=HH ; WITH_RAVEN=0 ; WITH_FUTURES=0
    - python: "3.5"
      env: TORNADO_VERSION=3.2.2 ; WITH_RAVEN=1 ; WITH_FUTURES=0
install:
  - if [[ $TORNADO_VERSION == 'HH' ]]; then pip install https://github.com/hhru/tornado/archive/fix-version.zip; else pip install tornado==$TORNADO_VERSION; fi
  - if [[ $WITH_RAVEN == 1 ]]; then pip install "raven < 5.2"; fi
  - if [[ $WITH_FUTURES == 1 ]]; then pip install futures; fi
  - pip install codecov
  - python setup.py install
  - mkdir ~/.python-eggs
  - chmod og-wx ~/.python-eggs
script:
  - python setup.py test
sudo: false
after_success:
  - ./coverage-run.sh
  - codecov
